/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const flashsales_ApproveSale = require('./code/flashsales-approveSale');
const flashsales_StartSale = require('./code/flashsales-startSale');
const flashsales_RejectSale = require('./code/flashsales-rejectSale');
const flashsales_EndSale = require('./code/flashsales-endSale');

class flashsalesSrv extends LCAPApplicationService {
    async init() {

        this.on('approveSale', 'FlashSales', async (request, next) => {
            return flashsales_ApproveSale(request);
        });

        this.on('startSale', 'FlashSales', async (request, next) => {
            return flashsales_StartSale(request);
        });

        this.on('rejectSale', 'FlashSales', async (request, next) => {
            return flashsales_RejectSale(request);
        });

        this.on('endSale', 'FlashSales', async (request, next) => {
            return flashsales_EndSale(request);
        });

        return super.init();
    }
}


module.exports = {
    flashsalesSrv
};